##############################
# 🏗️ 1. STAGE BUILDER
##############################
FROM python:3.11-slim AS builder

# Dossier de travail
WORKDIR /app

# Installer les dépendances dans un environnement isolé
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt
RUN pip install --no-cache-dir --prefix=/install gunicorn
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt



##############################
# 🚀 2. STAGE FINAL
##############################
FROM python:3.11-slim

# Dossier de travail
WORKDIR /app

# Copier uniquement ce qui est nécessaire depuis le builder
COPY --from=builder /install /usr/local
COPY . .

# Créer un utilisateur non-root
RUN adduser --disabled-password --gecos '' appuser \
    && chown -R appuser /app

# Basculer sur l'utilisateur sécurisé
USER appuser

# Exposer le port
EXPOSE 5000

# Lancer gunicorn (serveur WSGI de production)
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
